### PR TITLE
New direction of rotations, joint limits and updated human inspired limits

### PR DESCRIPTION
**Pull request by rsantos88**
* new joint limit values reviewed of arms and legs in the tables ods and csv
* changed diagram of directions: svg and png 
* new direction of rotations for arms and legs applied in the tables ods and csv
* updated the human inspired limits

### CODE REVIEW

**Comment by jgvictores** [comment]
WIP or ready to merge?

**Comment by rsantos88** [comment]
Ready to merge. If you've some time, you can take it a look.

**Comment by jgvictores** [comment]
Maybe we should update the `Sent. Giro` column?

**Comment by rsantos88** [comment]
totally true. We change it or we remove it?

**Comment by jgvictores** [comment]
Yes, let's remove it!

**Comment by rsantos88** [comment]
Ready to merge

**Pull request merged**
